const ADD_ITEM = "TODO_LIST/TODO_LIST/ADD_ITEM";
const DELETE_ITEM = "TODO_LIST/TODO_LIST/DELETE_ITEM";
const DONE_ITEM = "TODO_LIST/TODO_LIST/DONE_ITEM";
const IMPORTANT_ITEM = "TODO_LIST/TODO_LIST/IMPORTANT_ITEM";
const SET_MATCH = "TODO_LIST/TODO_LIST/SET_MATCH";
const SET_FILTER = "TODO_LIST/TODO_LIST/SET_FILTER";
const FIND_ELEMENT = "TODO_LIST/TODO_LIST/FIND_ELEMENT";
const UPD_TEXT = "TODO_LIST/TODO_LIST/UPD_TEXT";
const EDIT_LABEL = "TODO_LIST/TODO_LIST/EDIT_LABEL";

export {
    ADD_ITEM,
    DELETE_ITEM,
    DONE_ITEM,
    IMPORTANT_ITEM,
    SET_MATCH,
    SET_FILTER,
    FIND_ELEMENT,
    UPD_TEXT,
    EDIT_LABEL
};
